# syntax=docker/dockerfile:1

## Build
FROM golang:1.17-alpine AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . .

RUN go build -o /charmander

## Deploy
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /charmander /charmander

EXPOSE 9898

USER nonroot:nonroot

ENTRYPOINT [ "/charmander" ]
